var baseUrl="http://api.khareedto.com/api/web/";app=angular.module("Creators",["app.core","angular-loading-bar","app.routes","app.settings"]);
!function(){"use strict";angular.module("app.core",["ui.router","ngAnimate","ngStorage"])}();
!function(){"use strict";function e(e,r,i,o,t){var a=angular.module("app.core");a.controller=e.register,a.directive=r.directive,a.filter=i.register,a.factory=o.factory,a.service=o.service,a.constant=o.constant,a.value=o.value,t.classNameFilter(/^((?!(ng-no-animation)).)*$/)}angular.module("app.core").config(e),e.$inject=["$controllerProvider","$compileProvider","$filterProvider","$provide","$animateProvider"]}();
!function(){"use strict";angular.module("app.core").constant("CONFIG",{baseUrl:"http://"})}();
!function(){"use strict";function t(t,o,e,n,r){t.$state=o,t.$stateParams=e,t.$storage=n.localStorage,t.cancel=function(t){t.stopPropagation()},t.$on("$stateNotFound",function(t,o){console.log(o.to),console.log(o.toParams),console.log(o.options)}),t.$on("$stateChangeError",function(t,o,e,n,r,a){console.log(a)}),t.$on("$stateChangeSuccess",function(){n.scrollTo(0,0),t.currTitle=o.current.title}),t.currTitle=o.current.title,t.pageTitle=function(){var o=t.app.name+" - "+(t.currTitle||t.app.description);return document.title=o,o},r.version||(r.cart="",r.version=.1)}angular.module("app.core").run(t),t.$inject=["$rootScope","$state","$stateParams","$window","$localStorage"]}();
!function(){"use strict";angular.module("app.routes",[])}();
!function(){"use strict";function t(t,e,a,r){e.html5Mode(!0),r.otherwise("/home"),t.state("app",{url:"","abstract":!0,templateUrl:a.basepath("pages/app.html"),controller:function(){}}).state("app.index",{url:"/home",title:"Home",templateUrl:a.basepath("pages/home.html?v=2")}).state("app.privacy",{url:"/privacy",title:"Privacy Policy",templateUrl:a.basepath("pages/privacy.html")}).state("app.aboutus",{url:"/aboutus",title:"About Us",templateUrl:a.basepath("pages/aboutus.html")}).state("app.mycart",{url:"/mycart",title:"My Cart",templateUrl:a.basepath("pages/mycart.html")}).state("app.product",{url:"/product/:product",title:"Product",templateUrl:a.basepath("pages/product.html")})}angular.module("app.routes").config(t),t.$inject=["$stateProvider","$locationProvider","RouteHelpersProvider","$urlRouterProvider"]}();
!function(){"use strict";function e(){function e(e){return"views/"+e}return{basepath:e,$get:function(){return{basepath:e}}}}angular.module("app.routes").provider("RouteHelpers",e)}();



!function(){"use strict";angular.module("app.settings",[])}();
"use strict";function HomeController(t,a,r,o,c,e,n){t.formError="",t.selectedProduct="",t.cartFill=1,t.contact={email:"",message:"",failed:0,sent:0},t.products={},t.orderPlaced=0,t.checkoutMessage="#Order",t.placingOrder=0,t.formFill={name:"",email:"",phone:""},0==n.object().cart.length&&(t.initData=n.start(e.cart),t.data={cart:t.initData.cart},t.totalQuantity=t.initData.totalQuantity,t.cartTotal=t.initData.cartTotal),c.$on("cartModified",function(){t.data=n.object(),t.cartTotal=t.data.cartTotal,t.totalQuantity=t.data.totalQuantity,e.cart=t.data.cart,console.log(t.data.cart)});var i=function(){};t.load=function(){a({method:"GET",url:baseUrl+"products"}).then(function(a){t.products=a.data.data},function(a){t.error=a.data,t.products=[]})},t.addToCart=function(t){n.add(t),c.$emit("cartModified")},t.addOneQuantity=function(t){n.add(t),c.$emit("cartModified")},t.minusOneQuantity=function(t){n.removeQty(t),c.$emit("cartModified")},t.resetAddedToCart=function(){c.cart.forEach(function(t){t.addedToCart=0,t.qty=0}),t.calculateTotal(),e.cart=JSON.stringify([]),i()},t.removeFromCart=function(t){n.remove(t),c.$emit("cartModified")},t.placeOrder=function(){t.formError="",t.placingOrder=1,a({method:"post",url:baseUrl+"orders/place",data:{form:t.formFill,products:t.data.cart}}).then(function(a){console.log(a),t.orderPlaced=1,t.checkoutMessage="#ThankYou",t.placingOrder=0,n.clearAll(),c.$emit("cartModified")},function(a){t.formError=a.data.errors,console.log(a.data),t.placingOrder=0})},t.calculateTotal=function(){var t=0,a=0;c.cart.forEach(function(r,o){1==r.addedToCart&&(a+=r.qty,t+=r.qty*r.sprice)}),c.cartTotal=t,c.totalQuantity=a},t.sendContact=function(){t.contact.action="Please Wait...",t.errors="",a({url:baseUrl+"sendContact",method:"post",data:{email:t.contact.email,message:t.contact.message}}).then(function(){t.contact.sent=1},function(a){t.contact.action="",t.contact.failed=1,t.contact.errors=a.data.errors})}}angular.module("app.routes").factory("cartService",["$rootScope","$localStorage",function(t,a){var r=[],o=[],c=0,e=0,n=function(t){var a=-1;return o.forEach(function(r,o){r.code==t.code&&(a=o)}),a};return{start:function(t){return r=[],t&&(r=t),r.length&&r.forEach(function(t,a){t.qty>0&&(o.push(t),c+=t.qty*t.sprice,e+=t.qty)}),{cart:o,cartTotal:c,totalQuantity:e}},object:function(){return{cart:o,cartTotal:c,totalQuantity:e}},add:function(a){var r=n(a);-1==r?(o.push(a),e+=1,a.qty=1,c+=a.sprice):(o[r].qty+=1,e+=1,c+=a.sprice),t.cart=JSON.stringify(o)},removeQty:function(a){var r=n(a);if(-1!=r){if(1==o[r].qty){var i=[];o.forEach(function(t){t.code!==a.code&&i.push(t)}),o=i}else o[r].qty-=1;e-=1,c-=a.sprice,t.cart=JSON.stringify(o)}},remove:function(a){var r=[];o.forEach(function(t){t.code!==a.code&&r.push(t)}),c-=a.qty*a.sprice,e-=a.qty,o=r,t.cart=JSON.stringify(o)},clearAll:function(){o=[],c=0,e=0}}}]).controller("HomeController",HomeController);
"use strict";function myCartController(t,a,o,r,e,c,n){t.orderPlaced=0,t.checkoutMessage="#Order",t.placingOrder=0,t.formFill={name:"",email:"",phone:""},0==n.object().cart.length&&(t.initData=n.start(c.cart),t.data={cart:t.initData.cart},t.totalQuantity=t.initData.totalQuantity,t.cartTotal=t.initData.cartTotal),e.$on("cartModified",function(){t.data=n.object(),t.cartTotal=t.data.cartTotal,t.totalQuantity=t.data.totalQuantity,c.cart=t.data.cart,console.log(t.data.cart)}),e.$emit("cartModified"),t.placeOrder=function(){t.formError="",t.placingOrder=1,a({method:"post",url:baseUrl+"orders/place",data:{form:t.formFill,products:t.data.cart}}).then(function(a){console.log(a),t.orderPlaced=1,t.checkoutMessage="#ThankYou",t.placingOrder=0,n.clearAll(),e.$emit("cartModified")},function(a){t.formError=a.data.errors,console.log(a.data),t.placingOrder=0})},t.addToCart=function(t){n.add(t),e.$emit("cartModified")},t.addOneQuantity=function(t){n.add(t),e.$emit("cartModified")},t.minusOneQuantity=function(t){n.removeQty(t),e.$emit("cartModified")},t.removeFromCart=function(t){n.remove(t),e.$emit("cartModified")},t.calculateTotal=function(){var t=0,a=0;e.cart.forEach(function(o,r){1==o.addedToCart&&(a+=o.qty,t+=o.qty*o.sprice)}),e.cartTotal=t,e.totalQuantity=a},t.sendContact=function(){t.contact.action="Please Wait...",t.errors="",a({url:baseUrl+"sendContact",method:"post",data:{email:t.contact.email,message:t.contact.message}}).then(function(){t.contact.sent=1},function(a){t.contact.action="",t.contact.failed=1,t.contact.errors=a.data.errors})}}angular.module("app.routes").controller("myCartController",myCartController);
"use strict";function NavController(t,o,a,l,n,c){t.data=c.object(),t.cartTotal=t.data.cartTotal,t.totalQuantity=t.data.totalQuantity,n.$on("cartModified",function(){t.data=c.object(),t.cartTotal=t.data.cartTotal,t.totalQuantity=t.data.totalQuantity}),t.init=function(){t=n},t.print=function(){console.log(n.cart)},t.removeProduct=function(t){console.log(t),console.log(n.cart.splice(t,1))}}angular.module("app.routes").controller("NavController",NavController);
"use strict";function ProductController(o,r,t,l,u,e){}angular.module("app.routes").controller("ProductController",ProductController);

!function(){"use strict";function e(e){e.app={name:"KhareedTo",url:"http://khareedto.com",description:"Grab Your needs with one click",year:(new Date).getFullYear(),layout:{isFixed:!0,isCollapsed:!1,isBoxed:!1,isRTL:!1,horizontal:!1,isFloat:!1,asideHover:!1,theme:"app/css/theme-d.css",asideScrollbar:!1},useFullLayout:!1,hiddenFooter:!1,offsidebarOpen:!1,asideToggled:!1,viewAnimation:"ng-fadeInUp"},e.app.layout.horizontal="app-h"===e.$stateParams.layout}angular.module("app.settings").run(e),e.$inject=["$rootScope"]}();